### ISSUE TITLE
3.0.0. SNAPSHOT - BKBookieHandleNotAvailableException

### ISSUE THREAD

**Issue by aluccaroni** [diennea/bookkeeper-visual-manager#105]
Testing the 3.0.0. SNAPSHOT after https://github.com/diennea/bookkeeper-visual-manager/pull/101 I see that the bookie list is not loaded at startup and, If I force a reload, not all bookie are correctly reloaded.

Please note that this cluster has some "old" dead bookies

```
INFO: Discovered Bookie mn1-core2:1821
java.util.concurrent.ExecutionException: org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
        at org.bkvm.bookkeeper.BookkeeperManager.doRefreshMetadataCache(BookkeeperManager.java:227)
        at org.bkvm.bookkeeper.BookkeeperManager.lambda$refreshMetadataCache$3(BookkeeperManager.java:182)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
        at org.apache.bookkeeper.discover.ZKRegistrationClient.getBookieServiceInfo(ZKRegistrationClient.java:248)
        ... 8 more
Nov 25, 2020 1:48:37 PM org.bkvm.bookkeeper.BookkeeperManager doRefreshMetadataCache
SEVERE: Cannot refresh metadata {}
java.util.concurrent.ExecutionException: org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063)
        at org.bkvm.bookkeeper.BookkeeperManager.doRefreshMetadataCache(BookkeeperManager.java:227)
        at org.bkvm.bookkeeper.BookkeeperManager.lambda$refreshMetadataCache$3(BookkeeperManager.java:182)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.bookkeeper.client.BKException$BKBookieHandleNotAvailableException: Bookie handle is not available
        at org.apache.bookkeeper.discover.ZKRegistrationClient.getBookieServiceInfo(ZKRegistrationClient.java:248)
        ... 8 more
```

**Comment by aluccaroni** [comment]
Closed by https://github.com/diennea/bookkeeper-visual-manager/pull/106
